### ISSUE TITLE
Error with lock file

### ISSUE THREAD

**Issue by jonasbostoen** [orbitdb/orbit-db-cli#25]
I've been using orbit-db in my nodejs projects, which works really great btw! However, when trying to query databases created with nodejs, I get a weird error. For example, this command: `orbitdb info orbitdb/<hash>/<db_name>`, gives me this error: `Error: Lock FcntlFlock of <example_path>/orbitdb/ipfs/repo.lock failed: EBADF, Bad file descriptor`.

No idea what that means.

**Comment by Vishal1010101** [comment]
I am creating orbitdb database from cli and it gives the same error
`orbitdb create hello feed
Error: Lock FcntlFlock of /Users/apple/node_modules/orbit-db/orbitdb/ipfs/repo.lock failed: EINVAL, Invalid argument
/Users/apple/.nvm/versions/node/v11.10.0/lib/node_modules/orbit-db-cli/node_modules/yargs/yargs.js:1101
      else throw err
           ^

Error: Command failed: node "/Users/apple/.nvm/versions/node/v11.10.0/lib/node_modules/orbit-db-cli/src/bin" create /orbitdb/demo docstore
Error: Lock FcntlFlock of /Users/apple/node_modules/orbit-db/orbitdb/ipfs/repo.lock failed: EINVAL, Invalid argument

    at checkExecSyncError (child_process.js:637:11)
    at execSync (child_process.js:674:13)
    at CLI (/Users/apple/.nvm/versions/node/v11.10.0/lib/node_modules/orbit-db-cli/src/cli.js:6:10)
    at Object.exports.handler (/Users/apple/.nvm/versions/node/v11.10.0/lib/node_modules/orbit-db-cli/src/commands/demo.js:33:19)
    at Object.runCommand (/Users/apple/.nvm/versions/node/v11.10.0/lib/node_modules/orbit-db-cli/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/apple/.nvm/versions/node/v11.10.0/lib/node_modules/orbit-db-cli/node_modules/yargs/yargs.js:1014:30)
    at Object.get [as argv] (/Users/apple/.nvm/versions/node/v11.10.0/lib/node_modules/orbit-db-cli/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/apple/.nvm/versions/node/v11.10.0/lib/node_modules/orbit-db-cli/src/bin.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
Apples-MacBook-Pro-273:orbit-db apple$ orbitdb create hello feed
Error: Lock FcntlFlock of /Users/apple/node_modules/orbit-db/orbitdb/ipfs/repo.lock failed: EINVAL, Invalid argument
`
Can anyone help?
