### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by danielgamboar** [orbitdb/orbit-db-cli#29]
I have been trying to install and use orbit-db-cli. After installing it via npm and git clone. 

Via npm, it gets installed with no issue, when typing `orbitdb` in the command line, it shows the following:
`danieldev@danieldev:~$ orbitdb
/home/danieldev/orbit-db-cli/node_modules/leveldown/node_modules/bindings/bindings.js:99
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/danieldev/orbit-db-cli/node_modules/leveldown/build/leveldown.node
 → /home/danieldev/orbit-db-cli/node_modules/leveldown/build/Debug/leveldown.node
 → /home/danieldev/orbit-db-cli/node_modules/leveldown/build/Release/leveldown.node
 → /home/danieldev/orbit-db-cli/node_modules/leveldown/out/Debug/leveldown.node
 → /home/danieldev/orbit-db-cli/node_modules/leveldown/Debug/leveldown.node
 → /home/danieldev/orbit-db-cli/node_modules/leveldown/out/Release/leveldown.node
 → /home/danieldev/orbit-db-cli/node_modules/leveldown/Release/leveldown.node
 → /home/danieldev/orbit-db-cli/node_modules/leveldown/build/default/leveldown.node
 → /home/danieldev/orbit-db-cli/node_modules/leveldown/compiled/12.8.0/linux/x64/leveldown.node
    at bindings (/home/danieldev/orbit-db-cli/node_modules/leveldown/node_modules/bindings/bindings.js:96:9)
    at Object.<anonymous> (/home/danieldev/orbit-db-cli/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/danieldev/orbit-db-cli/node_modules/orbit-db-keystore/index-nodejs.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:868:30) {
  tries: [
    '/home/danieldev/orbit-db-cli/node_modules/leveldown/build/leveldown.node',
    '/home/danieldev/orbit-db-cli/node_modules/leveldown/build/Debug/leveldown.node',
    '/home/danieldev/orbit-db-cli/node_modules/leveldown/build/Release/leveldown.node',
    '/home/danieldev/orbit-db-cli/node_modules/leveldown/out/Debug/leveldown.node',
    '/home/danieldev/orbit-db-cli/node_modules/leveldown/Debug/leveldown.node',
    '/home/danieldev/orbit-db-cli/node_modules/leveldown/out/Release/leveldown.node',
    '/home/danieldev/orbit-db-cli/node_modules/leveldown/Release/leveldown.node',
    '/home/danieldev/orbit-db-cli/node_modules/leveldown/build/default/leveldown.node',
    '/home/danieldev/orbit-db-cli/node_modules/leveldown/compiled/12.8.0/linux/x64/leveldown.node'
  ]
}
`
I;ve tryed using the following node versions:
`danieldev@danieldev:~$ nvm ls
        v8.10.0
        v8.12.0
       v10.16.2
->      v12.8.0
default -> node (-> v12.8.0)
node -> stable (-> v12.8.0) (default)
stable -> 12.8 (-> v12.8.0) (default)
iojs -> N/A (default)
lts/* -> lts/dubnium (-> v10.16.2)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.16.0 (-> N/A)
lts/dubnium -> v10.16.2`

Any idea how to solve this situation?

**Comment by danielgamboar** [comment]
I have resolved this situation. As I'm using a Virtual Machine I decide to create a new VM to have a virgin installation of Ubuntu 18.04. I installed via nvm node v10.16.3, installed via npm git and python 2.7, then installed via npm orbit-db-cli and now I can access to orbitdb command.

**Comment by tymmesyde** [comment]
Same issue with node v12.17.0
